---
title: "Forked HW"
author: "Matthew Martignoni, Zhiang Chen"
date: "2022-11-4"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Setting Libraries

```{r}
library(sf)
library(tmap)
library(tmaptools)
library(RSQLite)
library(tidyverse)
library(leaflet)
library(leafpop)
library(janitor)
library(dplyr)
library(readr)
library(OpenStreetMap)
library(countrycode)
```

### Reading in Data

```{r}
# read shape file
shape <- st_read("data/World_Countries_(Generalized)/World_Countries__Generalized_.shp")

# read gender index data
gii_data_raw <- read_csv("data/HDR21-22_Composite_indices_complete_time_series.csv") 
```

### Manipulating Data
```{r}
# mutate shape file 2 characters ISO to 3 characters ISO
shape$ISO3 <- countrycode(shape$ISO, origin = 'iso2c', destination = 'iso3c')

# select column
gii_data_raw_2 <- select(gii_data_raw, iso3, country, gii_2010, gii_2019)

# delete non-country column
gii_data_raw_3 <- head(gii_data_raw_2, - 11) 

# caculate the difference between 2010 and 2019
# I've changed the order of calculating difference because now it will show the *decrease* in inequality, so now the increase of equality. If you look at the data, there was more inequality in 2010 and there is less today 
gii_data_raw_3$diff <- gii_data_raw_3$gii_2010-gii_data_raw_3$gii_2019

#change to percent increase/decrease so the map is more easily understandable
gii_data_raw_3$diff_percent <- gii_data_raw_3$diff*100

final_data <- select(gii_data_raw_3, iso3, diff_percent)
```

### Joining Data
```{r}
# join data
shape2 <- shape %>%
  merge(.,
        final_data,
        by.x="ISO3", 
        by.y="iso3",
        all.x=TRUE)
```

### Initial Map Making
```{r}
tm_shape(shape2) + 
tm_polygons("diff_percent", 
        style="jenks",
        n = 10,
        palette="RdYlGn",
        midpoint=NA,
        title="Percent Increase",
        legend.hist=TRUE) +
  tm_layout(title = "Gender Inequality Increase by Percentage from 2010 to 2019", legend.outside = TRUE)
```

### Adding New Maps

```{r}

Map1 <- 
  
```



